OneSignal/OneSignal-Unity-SDK

- buildpackage.sh
• Adds a build shell script at the root of the repo to let devs easily build the unity package
• Automatically excludes unnecessary files (icons, jars, etc) from the build
• Allows devs to pass in the filename as an argument (but defaults to OneSignalSDK.unitypackage)
> Package Build Script

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• Previously, the build script was generating a notification service extension that only targeted iPhones on iOS 11.3
• Now supports Universal target with deployment target of 10.0
> Universal Notification Service Extension Target Support

- OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignalUnityRuntime.m
• Fixes an issue where a swizzled implementation of the UNUserNotificationCenter.setDelegate() method was not calling back to the original implementation if it had previously been set.
> Swizzling Fix

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• The build script that automatically injects required frameworks and adds the push notification service extension for iOS was using unity API's that were not supported in older versions of unity.
• Added compiler flag checks to ensure that the build script doesn't attempt to use API's that are not available in the developer's unity version.
resolves #114
> Buildscript compatibility

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• Unity Cloud Build does not support provisioning/signing for app extensions (such as the notification service extension that our buildscript automatically generates)
• Added preprocessor checks to ensure that in the unity cloud build env, the build script doesn't attempt to add the extension service as it will cause a build failure.
• Until Unity adds support for signing extensions, we recommend developers build on their own machines as it is valuable to have the extension service.
> Unity Cloud Build Compatibility

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• Fixes an issue that caused an error to be printed to the Unity console when the developer attempted to rebuild their project (instead of generating a new Xcode project)
• The build script attempted to copy a file (for the OneSignalNotificationServiceExtension) that would already have existed, causing an error.
> Fix Rebuild Issue

- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorCheckUpdateScript.cs
- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• Switches away from using hardcoded directory separator characters to using platform-dependent separators in the build script and update checker script
• Resolves #132
> Platform-Dependent Directory Separator Character

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
• Fixes an issue where the iOS Unity buildscript was mistakenly copying a template header file from our assets directory into generated projects as both the header and implementation (.m) files. 
• Because interfaces are allowed to existing in Objective-C implementation files, this did not cause build errors or warnings, but would have resulted in no class implementation for the extension service class. This means rich push notifications would not have worked correctly
• Unfortunately we've never had tests in our unity SDK - we are considering adding a test suite in the future to catch such issues
• Fixes an issue where our iOS buildscript was using the correct directory separator character (`\` in windows, `/` in most other environments), but when generating the Xcode project, it was …
> Buildscript extension fix

- OneSignalExample/Assets/OneSignal/Editor/OneSignalDependencies.xml
* Changed version range dependencies to use '[' instead of '(' due to a bug with play-services-resolver 1.2.88.0+
* This relates to issue https://github.com/googlesamples/unity-jar-resolver/issues/151
* This resolves #146
> Fix for play-services-resolver 1.2.88.0 w/ Android

- OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
- OneSignalExample/Assets/OneSignal/Platforms/iOS/Info.plist
- OneSignalExample/Library/ProjectSettings.asset
- OneSignalExample/ProjectSettings/ProjectSettings.asset
* Unity 2019.3+ detection to use the new GetUnityMainTargetGuid and GetUnityFrameworkTargetGuid methods
* Added notification background mode per the code suggested in issue #175.
* Fixed overwriting LIBRARY_SEARCH_PATHS
- This fixes -liPhone-lib and -lOneSignal errors related to this as well
* Fixed overwriting .entitlements file
- Existing file is now read and appended.
* Fixed missing App Groups on the NotificationServiceExtension target
* Fixed plist versions not updating on Append builds on the NotificationServiceExtension target
- This fixes warnings in Xcode when Archiving the app if the app version number was updated in Unity.
* Now supports Unity iOS builds on Windows
- Projects copied to macOS build correctly in Xcode after now.
* Lots of clean up and refactoring
* Fixed default …
> Fixed Unity 2019.3 and other iOS build fixes

- OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignalUnityRuntime.m
* This fixes the follow runtime iOS error when clicking on an IAM action
without an actionName set.
`Uncaught exception: NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]`
Fixes #292
> Added iOS IAM nil check to clickName

- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorCheckUpdateScript.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorScriptInit.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorScript_Android.cs
Incorporate some of the structure(`OneSignalEditorScriptInit`) and helpers(`OneSignalFileLocator`) introduced in PR #336 to the rest of the code base to improve code quality.
Tested on Windows 10 with Unity 2020.2.2f1.
* Ensured `AndroidManifest.xml` is correctly generated from `AndroidManifestTemplate.xml`.
> Code Quality - Align rest of code base to use OneSignalEditorScriptInit & OneSignalFileLocator added in PR #336

- OneSignalExample/.gitignore
- OneSignalExample/Assets/OneSignal/Editor/OSUnityEditorUtils.cs
- OneSignalExample/Assets/OneSignal/Editor/OSUnityEditorUtils.cs.meta
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorCheckUpdateScript.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorScriptInit.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorScriptInit.cs.meta
- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorScript_Android.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalFileLocator.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalFileLocator.cs.meta
- OneSignalExample/Assets/OneSignal/Editor/OneSignalFileStructureUpgrade.cs
- OneSignalExample/Assets/OneSignal/Editor/OneSignalFileStructureUpgrade.cs.meta
- buildpackage.sh
When someone updates to the latest SDK by importing it's `.unitypackage` file the `OneSignalConfig` folder does not get renamed to `OneSignalConfig.plugin` required for the fix in PR #335 to work.
Solution B noted below is implemented in this PR.
I attempt to first change the GUID in the `OneSignalConfig.plugin.meta` file, hoping Unity would think this is new and move all it's child files. It ignores it as I assume this is due the fact that the `.meta` of all the child files did not change. If we give all new GUIDs to these files than it would result in having a `OneSignalConfig.plugin` folder with all files we want it however "OneSignalConfig" would stick around. These duplicate files would create build issues so this won't work.
This seems pretty feasible after discovering the …
> Rename OneSignalConfig -> OneSignalConfig.plugin via an editor script - Fix up to PR #335

- OneSignalExample/Assets/Plugins/Android/OneSignalConfig.plugin/AndroidManifestTemplate.xml
* Defining `minSdkVersion` in the `AndroidManifest.xml` is a lint error with Android Gradle builds so this was removed.
- This used to be required for much other version of Unity not using Gradle to build. As with ANT it would default to 1 which would create other build issues.
* This fixes Android build errors on new Unity 2020.2 projects.
* Tested this is not needed any longer back to Unity 2018.4.31 as well
* Fixes #281
> Remove Android minSdkVersion to fix build error due to lint problem

- OneSignalExample/Assets/OneSignal/Editor/OneSignalEditorCheckUpdateScript.cs
* Cleans up `UnityWebRequest` warnings in Unity 2020.1 and newer.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/345)
> Clean up update checker Unity 2020 editor warnings

- com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs
Re: https://github.com/OneSignal/OneSignal-Unity-SDK/issues/375
FileUtil.CopyFileORDirectory documentation explicitly requires all pathing to use forward slashes: https://docs.unity3d.com/ScriptReference/FileUtil.CopyFileOrDirectory.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/376)
> Fix critical build error

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Mappings.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/Models/NotificationPermission.cs
- com.onesignal.unity.core/Runtime/Models/NotificationPermission.cs.meta
- com.onesignal.unity.core/Runtime/Models/PermissionState.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Callbacks.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Added in missing getters for the permission and subscription states
- `PermissionState` has been removed and the `NotficationPermission` enum is reported in its place.
- Associated event `PermissionStateChanged` has been renamed to `NotificationPermissionChanged`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/421)
> [Fix] Missing getters for subscription states and push permissions

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Added missing setter for language which will allow overriding of the default detected language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/422)
> [FIX] Added missing language setter

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/OneSignal.Internal.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.core/Runtime/OneSignalBehaviour.cs
- com.onesignal.unity.core/Runtime/Utilities/SDKDebug.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Properly push `LogLevel` and `AlertLevel` settings to native SDKs
- `LogLevel` and `AlertLevel` now use a custom enum setup to mimic native implementations instead of the Unity `LogType`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/423)
> [Fix] Properly push log level settings to native SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/Utilities/AndroidJavaObjectExtensions.cs
- Eliminated syntax only supported on Unity 2020 or above
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/426)
> [Fix] Removed unsupported syntax

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- Global callbacks on Android are now correctly setup post `initWithContext`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/424)
> [Fix] Setup Android global callbacks post initWithContext

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- `NotificationPermission` return from native SDK no longer raises a casting exception on iOS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/433)
> [FIX] Exception on get NotificationPermission

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.core/Runtime/OneSignal.Internal.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- Resolved infinite loops on logging initialization conditions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/432)
> [FIX] Use default debug logging on initialization

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- iOS postprocessing will respect existing entitlement files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/435)
> [FIX] iOS postprocessing will not overwrite existing entitlements

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/Editor/Setup/OneSignalSetupWindow.cs
- com.onesignal.unity.android/Editor/SetupSteps/InstallEdm4uStep.cs
- com.onesignal.unity.core/Editor/Setup/OneSignalSetupWindow.cs
- com.onesignal.unity.core/Editor/SetupSteps/SyncCodeBundleStep.cs
- com.onesignal.unity.core/Editor/SetupSteps/SyncCodeBundleStep.cs.meta
- com.onesignal.unity.core/Editor/Utilities/UnityPackageInstaller.cs
- com.onesignal.unity.core/Editor/Utilities/UnityPackageInstaller.cs.meta
To make it easier to update from 2.x to 3.x (as well as any future releases)
- Included a new setup step from the OneSignal Unity Editor menu (**Window > OneSignal**) which syncs the example code bundle with the core package version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/434)
> [FEATURE] Setup step to sync example code

- OneSignalExample/Assets/OneSignal/Attribution/VspAttribution.cs
- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroidInit.cs
- com.onesignal.unity.core/Runtime/OneSignal.Internal.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOSInit.cs
- Will no longer init SDK again if done before `RuntimeInitializeOnLoadMethod`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/437)
> [FIX] Initialized SDK twice if before RuntimeInitializeOnLoadMethod

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
- Froze imported OneSignal iOS SDK to [3.10.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.10.0) release
- Froze imported OneSignal Android SDK to [4.6.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.5) release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/439)
> [FEATURE] Freeze to latest platform SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs
- Log an error in the example app when `RequiresPrivacyConsent` is attempted to be set to false from true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/443)
> [IMPROVEMENT] Additional example logging around RequiresPrivacyConsent

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Callbacks.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Mappings.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Mappings.cs.meta
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- iOS callbacks for the `NotificationPermissionChanged` event will no longer cause an il2cpp exception
- Internal state mappings on iOS now rely on class defined objects over dynamic Dictionary types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/448)
> [FIX] il2cpp exception on NotificationPermissionChanged

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- Replaced manual manipulation of iOS entitlements in post processing with Unity's [ProjectCapabilityManager](https://docs.unity3d.com/ScriptReference/iOS.Xcode.ProjectCapabilityManager.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/447)
> [IMPROVEMENT] Replace legacy iOS capabilities postprocessing

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- Added podfile amendments to iOS Append builds. Previously, EDM4U generated a new podfile on Append builds and broke the OneSignal native extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/455)
> [IMPROVEMENT] Add podfile amendments to Append builds

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
This PR adds an issue template form to collect info needed to triage bug reports.
The form asks the following questions;
1. What happened?
2. What did you expect to happen?
3. What version of Unity are you running?
4. Which platform are you having an issue with?
5. Relevant log output
6. Code of conduct
If there are any other questions I should ask, feel free to drop a comment so I can incorporate the changes. Some things I'm not sure about are
1.  Which versions of Unity do we want to include in the dropdown?
2. Do we want to ask for specific version of iOS/Android
3. Should we ask which libraries are being used 
**[📝 Rendered form](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/484a65715435392e77cf5c7642e65940a83778ab/.github/ISSUE_TEMPLATE/BUG_REPORT.yml)**
* [Creating issue …
> Add issue template for bug reports

- OneSignalExample/Assets/OneSignal/Editor/PackageManagement/Manifest.cs
- OneSignalExample/Assets/OneSignal/Editor/Setup/OneSignalSetupWindow.cs
- OneSignalExample/Assets/OneSignal/Editor/Utilities/MiniJSON.cs
- OneSignalExample/Assets/OneSignal/Editor/Utilities/ReflectionHelpers.cs
Fix for error that didn't show up in https://github.com/OneSignal/OneSignal-Unity-SDK/pull/456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/458)
> Fix namespaces for tool copies in project package

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Main will be rolled back on merging this PR. `develop` has a ton of incoming changes and performing a rebase will lose that history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/460)
> [FIX] Bug Report targeting develop

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/PBXProjectExtensions.cs
- Removed unused helper method in the iOS post processor which used code from after Unity 2018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/463)
> [FIX] Removed code unsupported in Unity 2018

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Reimplemented support for `RemoveExternalUserId`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/475)
> [FIX] Missing RemoveExternalUserId

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Callbacks.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Mappings.cs
- iOS serialization of `Notification` type now accounts for `additionalData` and `rawPayload` in all cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/477)
> [FIX] Notification serialization on iOS

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs
- Added inline documentation and Unity idiomatic fields to the `InAppMessageAction`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)
> [FEATURE] InAppMessageAction docs and idiomatic fields

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/Info.plist
- Added prefix to the NSExtensionPrincipalClass in the NotificationServiceExtension Info.plist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/483)
> [FIX] NSExtensionPrincipalClass value

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs
- Explicitly check for a diff and handle overwrites for the `AndroidManifest.xml` between the project's and package's `OneSignalConfig.plugin`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488)
> [CHANGE] Overwrite project's AndroidManifest if diff

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
* Unity Build on Windows targeting iOS errors on Entitlements file.
Was able to reproduce the same issue and stack trace noted in issue #491 and confirm this fixed it.
* Windows 11 with Unity 2020.3.30f1
- Confirmed project also builds on macOS (with same mac env noted below)
* macOS 12.3.1 with Unity 2020.3.33f1 and Xcode 13.3
* iOS 14.4.1
Resolves #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/493)
> [FIX] Unity Build on Windows Targeting iOS errors on Entitlements file

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- `OneSignalXCFramework` pod version of `OneSignalNotificationServiceExtension` target in Podfile of iOS builds will be upgraded if target is present during post processing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/495)
> [FIX] Refresh service extension pod version on each build

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs
- `InstallEdm4uStep` checks for version number to determine if step is completed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496)
> [FEATURE] Check EDM4U Version

- MIGRATION.md
- README.md
Documented CocoaPods 1.11.3 or newer requirement on both the readme setup and the migration guide.
This is a required version, otherwise `pod install` runs without any errors but the Xcode project will fail to build with the error "No Such Module 'OneSignal'", as reported in issue #468.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/498)
> [Added] Documented CocoaPods 1.11.3 or newer requirement

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/Plugins/iOS/NotificationService.swift.meta
Omits `NotificationService.swift` from the `UnityFramework` Xcode target to fix an error when publishing the app to Apple.
This file doesn't need to be on the `UnityFramework` target and doing so means `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `Yes`. `This causes a STATE_ERROR.VALIDATION_ERROR.90206` error when the app is uploaded to Apple.
Fixes #500
Effect Xcode build settings.
* Xcode 13.3.1
* Unity 2020.3.33f1
* iOS 14.4.1
* iOS device - Ensured the NSE still runs and displayed an image on the notification.
* Upload to Apple is successful
* Ensured `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `No` on all targets in Xcode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [Fix] iOS publishing error 90206 "contains disallowed file 'Frameworks"

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
Check for presence of NSE in the project rather than just one of its required files.
Stability improvement when generating the iOS project if for some reason the plist was altered before an append build.
Tested and ran iOS builds in Unity 2018 - 2021 latest versions.
- [x ] I have personally tested this on my device, or explained why that is not possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/503)
> [FIX] NSE checks on build

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
Added support for OneSignal Android `setLanguage` callbacks
Provides `setLanguage` callback functionality from the native OneSignal Android SDK to the Unity SDK.
Tested setLanguage call and logged callback in app built with Android Studio 2021.2 on a Pixel 6 with Android 12.
> [FEATURE] setLanguage callback for Android

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
Updates the included OneSignal iOS SDK to the latest version, [3.11.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.2).
Keeps iOS builds made with the OneSignal Unity SDK up to date with changes made in the native OneSignal iOS SDK.
Tested push notifications using NSE features (badge, media attachments, action buttons), app build with Unity Editor 2021.3.0f1 of the Unity Example App on an iPhone 12 with iOS 15.3.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/519)
> [FEATURE] Update iOS SDK version

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Updates the included OneSignal Android SDK to the latest version, [4.7.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.4).
Keeps Android builds made with the OneSignal Unity SDK up to date with changes made in the native OneSignal Android SDK.
Tested app build with Unity Editor 2021.3.0f1 of the Unity Example App on a Pixel 6 with Android 12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/520)
> [FEATURE] Update Android SDK

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
Added support for OneSignal Android functionality `promptForPushNotifications`
Add support for Android 13 notification permission prompt from the native OneSignal Android SDK.
Tested app build with Unity 2021.3.0f1 of the Unity Example App on a Pixel 4 simulator with Android 13.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/522)
> [FEATURE] promptForPushNotifications for Android

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.android/Runtime/Utilities/AndroidJavaObjectExtensions.cs
Fixes Android `DeleteTags` and `RemoveTriggers` calls to correctly use a Java array list instead of an array.
Fixes `JNI: Unknown signature` and `java.lang.NoSuchMethodError` errors from calling `DeleteTags` and `RemoveTriggers`.
Tested deleting tags and removing triggers on an app build with Unity 2021.3.2f1 of the Unity Example App on a Pixel 6 with Android 12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/526)
> [FIX] Java Collection type parameters for Android

- .github/workflows/activation.yml
Add GitHub action to generate Unity license.
Generates Unity license to use for the [game-ci](https://game.ci/) GitHub actions test runner and builder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/534)
> [Add] GitHub action to generate Unity license

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.core/Runtime/OneSignal.cs
It's very confusing to see 3.0.0 in the log messages when the package version is 3.0.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/549)
> Correct OneSignal.Version constant value

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
Updates the included OneSignal Android and iOS SDKs to the latest version.
Bumps Android SDK from [4.8.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.1) to [4.8.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.3).
Bumps iOS SDK from [3.11.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.2) to [3.11.5](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.5).
Tested OneSignal initialization, app build with Unity 2020.3.36f1 of the OneSignal example App on a Pixel 6 with Android 13 and iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/551)
> [FEATURE] Update Android & iOS SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
Fixes app group name not being dynamic. More info on this issue #545.
If a previous pre/post-process script changes the bundle identifier, OneSignal's BuildPostProcessor script uses the wrong bundle identifier and it is causing CI build errors.
No unit test here, not required.
Tested on a CI build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/555)
> Fixed app group name to be a property. Fixes [#545]

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
- com.onesignal.unity.ios/Editor/PBXProjectExtensions.cs
Fixes Android builds failing without the Unity iOS module.
Allows Android builds to compile without the Unity iOS module and fixes Android builds for CI builders. Addresses [#508](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/508)
Tested building the example app for Android without the Unity iOS module installed on 2020.3.41f1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/556)
> [Fix] Android builds without iOS modules

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
- com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
Adds live activity methods from the iOS SDK
iOS feature to allow entering and exiting live activities through OneSignal.
Tested calling exit and enter live activity methods on app build with Android 2021.3.1 on a Pixel 4 simulator with Android 12 and Xcode 14.1 build with a iOS iPhone 12 on iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/559)
> [Feature] Live activities

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.Mappings.cs
- com.onesignal.unity.core/Runtime/Models/Notification.cs
Resolved `The Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. …` warning log from appearing when a notification is opened or received.
Resolves warning log
The `Notification` `groupedNotifications` property is now a list of type `NotificationBase` instead of a list of type `Notification`.
Tested receiving and opening a notification, app build with Android 2021.3.1 with a fresh install of the OneSignal example app on a Pixel 4 simulator with Android 12 and Xcode 14.1 build with an iOS iPhone 12 on iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/567)
> [Fix] Serialization depth warning

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
- com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs
- com.onesignal.unity.core/Runtime/OneSignal.cs
- com.onesignal.unity.ios/Runtime/OneSignalIOS.cs
Renamed `enterLiveActivity` to `EnterLiveActivity` and `exitLiveActivity` to `ExitLiveActivity`
Fixes live activity method names to be capitalized
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/569)
> [Fix] Live activity method names

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Fixes Android build errors not finding OneSignal classes due to the Android OneSignal version being bumped to the next major version.
This prevents it from being bumped by EDM4U which can cause unpredictable behavior.
Critical fix for broken Android builds for most projects for all previous existing versions of OneSignal. This resolves #573 which was due to EDM4U bumping to the major 5.0.0 version of OneSignal which has breaking API changes. 
Only effects Android builds. Issue only when other libraries are also in the project that use newer versions of OneSignal's dependencies, however this is quite common.
None, no existing tests around this.
Tested with a new Unity project with:
* macOS 13.1
* Unity 2021.3.16f1
* FirebaseAuth 10.3.0
I reproduced the issue and ensured the locking change …
> [Fix] Lock OneSignal Android Version

- .github/workflows/release-drafter.yml
- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
Updates included OneSignal Android and iOS SDKs to the latest version.
Bumps Android SDK from [4.8.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.3) to [4.8.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.5).
Bumps iOS SDK from [3.12.3](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.3) to [3.12.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.4).
Tested OneSignal initialization, app build with Unity 2020.3.43f1 of the OneSignal example app on a emulated Pixel 4 with Android 12 and physical iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/595)
> [FEATURE] Update OneSignal Android and iOS SDK

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalBridgeUtil.h
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalBridgeUtil.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeInAppMessages.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm
Adds a helper method to the iOS plugin
Cleans up the internal code a bit
No external functionality should be affected
Tested adding and removing a trigger, alias, and tag. App build with Xcode 14.2 with the OneSignal example app on an iPhone 12 on iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/591)
> [User model] Add a helper method to the iOS plugin

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
Fix rare Android ANRs when OneSignal callbacks fire and when the app is backgrounded.
The time spent on the main thread in this scenario is significantly contributing to ANRs. The Google Play store penalizes apps with ANRs with lower search rankings and possibly some other negatives.
Only effects Android and threading used for callbacks, observers, and events like click.
These are the two PRs that were included in the OneSignal-Android-SDK 4.8.6 release this PR depends on:
* https://github.com/OneSignal/OneSignal-Android-SDK/pull/1775
* https://github.com/OneSignal/OneSignal-Android-SDK/pull/1776
None
Tested on Samsung S21 with Android 13. Ensured `SetExternalUserId`'s callback still fires in the example app here.
Also ensured the threading preference value did change by printing its …
> [Fix] ANRs for callbacks and when backgrounding app

- MIGRATION_GUIDE_v3_to_v5.md
- OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md
Add upgrade steps in the migration guide to tell users to delete old files manually before they upgrade.
Directly upgrading the SDK from 3.x.x to 5.x.x may cause `The type or namespace name '...' could not be found` and `Assets/OneSignal/Attribution/OneSignalVSAttribution.cs: error CS0117: 'OneSignal' does not contain a definition for '...'` errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/619)
> [User Model] Add upgrade steps to migration guide

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs
- com.onesignal.unity.core/Samples~/OneSignalExampleBehaviour.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm
Fixes malloc error on iOS when calling `OneSignal.User.PushSubscription.Id` or `OneSignal.User.PushSubscription.Token`.
Addresses reported issue https://github.com/OneSignal/OneSignal-Unity-SDK/issues/628, "pointer being freed was not allocated" when returning a string from the iOS bridge.
Tested logging push subscription Id and token, app build with Unity 2021.3.16f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/629)
> [Fix] Push subscription Id and Token on iOS

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeNotifications.mm
- com.onesignal.unity.ios/Runtime/iOSNotificationsManager.cs
Stop foreground notifications from displaying after calling prevent default on iOS
Fixes user reported bug  https://github.com/OneSignal/OneSignal-Unity-SDK/issues/628 where calling prevent default still displays the notification on iOS
Tested displaying a notification in the foreground, app build with Unity 2021.3.16f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/635)
> [Fix] PreventDefualt on iOS

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeNotifications.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/UIApplication+OneSignalUnity.mm
- com.onesignal.unity.ios/Runtime/iOSNotificationsManager.cs
Fixes iOS notifications clicked event to fire when the app was cold started from clicking a notification.
Fixes https://github.com/OneSignal/OneSignal-Unity-SDK/issues/638 iOS bug where Notifications.Clicked event is set but does not fire when clicking the notification cold starts the app.
Tested clicking on notifications when the app in the foreground, background, and closed, app build with Unity 2021.3.16f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/641)
> [Fix] iOS notifications clicked event to fire on cold start

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Updates included OneSignal Android SDK to [5.0.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2).
Bump OneSignal Android SDK to latest version to include native fixes
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a emulated Pixel 4 with Android 12.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/642)
> [Feature] Bump OneSignal Android SDK version

- MIGRATION_GUIDE_v3_to_v5.md
- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md
- OneSignalExample/Assets/OneSignal/README.md
- README.md
- com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
Fixes iOS "does not contain bitcode" build error by disabling bitcode
Prevent iOS builds from failing with default "Enable Bitcode" value and documents setting "Enable Bitcode" to "No".
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/645)
> [Fix] iOS bitcode build error

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/README.md
- README.md
Update documentation to make it clearer that `OneSignalConfig.plugin` has been changed to `OneSignalConfig.androidlib`
Make it clearer that custom notification icons are now located in `Assets/Plugins/Android/OneSignalConfig.androidlib/src/main/res` and that users should run the "Copy Android plugin to Assets" step in **Window > OneSignal SDK Setup** to migrate. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/649)
> [Fix] Documentation Nit

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.core/Editor/SetupSteps/SyncCodeBundleStep.cs
Fixes package download url in the "Sync example code bundle package" step from the OneSignal SDK Setup
Fixes `HTTP:1.1 404 Not Found` error when running the "Sync example code bundle package" setup step
Tested running the "Sync example code bundle package" OneSignal SDK Setup step in the Unity Editor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/657)
> [Fix] OneSignal SDK Setup package download url

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/OneSignaliOS.cs
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalBridgeUtil.h
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalBridgeUtil.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeDebug.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeInAppMessages.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeLiveActivities.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeLocation.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeNotifications.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeSession.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/UIApplication+OneSignalUnity.mm
- com.onesignal.unity.ios/Runtime/iOSDebugManager.cs
- com.onesignal.unity.ios/Runtime/iOSDisplayableNotification.cs
- com.onesignal.unity.ios/Runtime/iOSInAppMessagesManager.cs
- com.onesignal.unity.ios/Runtime/iOSLiveActivitiesManager.cs
- com.onesignal.unity.ios/Runtime/iOSLocationManager.cs
- com.onesignal.unity.ios/Runtime/iOSNotificationsManager.cs
- com.onesignal.unity.ios/Runtime/iOSPushSubscription.cs
- com.onesignal.unity.ios/Runtime/iOSSessionManager.cs
- com.onesignal.unity.ios/Runtime/iOSUserManager.cs
Adds "OneSignal" prefix to Objective-C methods to avoid name conflicts with other iOS plugins
Fixes #663
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [Fix] Add prefix to Obj-C methods

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/OneSignalConfig.androidlib/build.gradle
- com.onesignal.unity.android/Editor/OneSignalConfig.androidlib/build.gradle
Sets version numbers in the OneSignalConfig.androidlib build.gradle to match the versions specified in Unity
Fixes https://github.com/OneSignal/OneSignal-Unity-SDK/issues/670 READ_PHONE_STATE permission being added to Android builds
Fixes lower build-tools versions being needed for Android builds than the [version the Unity Editor comes with](https://docs.unity3d.com/Manual/android-sdksetup.html)
- I was able to reproduce a licensing 30.0.3 build-tools build error in a new project with the OneSignal SDK on Unity 2022.3.14 which comes with build-tools 32.0.0. The lower build-tools error version may differ depending on the Unity Editor version.
Not specifying a version number in the build.gradle sets it to a low version instead. minSDKVersion was set to 1 and added the READ_PHONE_STATE …
> [Fix] OneSignalConfig.androidlib version numbers in build.gradle

- OneSignalExample/Assets/Plugins/Android/OneSignalConfig.androidlib/build.gradle
- com.onesignal.unity.android/Editor/OneSignalConfig.androidlib/build.gradle
Fixes OneSignalConfig.androidlib minSdkVersion and targetSdkVersion Android build errors in Unity 2021
Fixes the following Android build error in Unity 2021.3.10 that occurs when calling `defaultConfig.minSdk` and similarly for `defaultConfig.targetSdk`. This error does not occur in Unity 2022.3.10.
```
A problem occurred evaluating project ':unityLibrary:OneSignalConfig.androidlib'.
> Could not get unknown property 'minSdk' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=22, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=30, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=0.1, …
```
> [Fix] OneSignalConfig.androidlib minSdkVersion and targetSdkVersion for Unity 2021

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/OneSignal/README.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- README.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updated included OneSignal Android SDK to [5.1.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.1) and OneSignal iOS SDK to [5.1.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.0)
Applies native fixes from the OneSignal Android SDK and OneSignal iOS SDK to the Unity SDK
- [OneSignal Android SDK 5.1.1 Release Notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.1)
- Includes location behaviour change from [5.1.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.0):
- You will need to include location permission in your own app's manifest
- [OneSignal iOS SDK 5.1.0 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.0)
Unity developers must target API level 33 or higher to build for …
> [Feature] Update native OneSignal SDKs dependencies to 5.1.x

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Updated included OneSignal Android SDK to [5.1.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.2)
Applies native fixes from the OneSignal Android SDKto the Unity SDK
- [OneSignal Android SDK 5.1.2 Release Notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.2)
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a emulated Pixel 4 with Android 12.
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like …
> [Feature]Update OneSignal Android SDK dependency to 5.1.2

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm
Fixes crash on iOS when calling OneSignal.User.PushSubscription.Id or OneSignal.User.PushSubscription.Token when they are null.
Fixes iOS crash caused by calling `strdup` with a null parameter.
Tested by initializing OneSignal with no wifi connection and calling OneSignal.User.PushSubscription.Id and OneSignal.User.PushSubscription.Token, app build with Unity 2022.3.10f1 with a fresh install of the OneSignal example app on a physical iPhone 12 with iOS 15.5.
- WIP (Work In Progress) is ok, but explain what is still in progress and …
> [Fix] iOS Null PushSubscription Id and Token crash

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Update Android dependency version to 5.1.5
Keep Unity wrapper up to date with the native
No testing needed for version bump
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/700)
> Update Android dependency version to 5.1.5

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
Updates the included native OneSignal SDKs to the latest player model version.
Updates Unity SDK to include changes and fixes from the Android and iOS SDK
Bumps Android SDK from [4.8.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.5) to [4.8.8](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.8).
- Fixes various ANRs
- See [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases) for full changes
Bumps iOS SDK from [3.12.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.4) to [3.12.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.9).
- Adds privacy manifests
- Fixes various iOS crashes
- See [release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases) for full changes
Tested …
> [Feature] Update native OneSignal SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.7 to [5.1.8](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.8) and OneSignal iOS SDK from 5.1.4 to [5.1.5](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.5)
Apply fixes made in the native SDKs to the Unity wrapper SDK.
Updated included Android SDK from 5.1.8 to [5.1.9](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.9)
- Added AndroidManifest option to override In-App Messages gray overlay and dropshadow
- \<meta-data android:name="com.onesignal.inAppMessageHideGrayOverlay" android:value="true"/>
- \<meta-data android:name="com.onesignal.inAppMessageHideDropShadow" android:value="true"/>
- Fixed WorkManager not initialized crash
- Fixed don't re-create user on failed remove alias
- …
> [Feat] Bump native OneSignal SDKs versions

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.10 to [5.1.13](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.13) and OneSignal iOS SDK from 5.1.6 to [5.2.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.0)
Apply fixes made in the native SDKs to the Unity wrapper SDK.
Updated included OneSignal Android SDK from 5.1.10 to [5.1.13](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.13)
- Fixed the ANR issue caused by prolonged loading of OperationRepo and potentially by extended holding of the model lock during disk I/O read operations
- Fixed IndexOutOfBounds exception thrown from OperationRepo.loadSavedOperations if app was opened offline, some operations done, and then the app is opened again
- Targets JDK11 instead of JDK21 to …
> [Feat] Update OneSignal Android and OneSignal iOS SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeDebug.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeInAppMessages.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeLiveActivities.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeLocation.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeNotifications.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeSession.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm
- com.onesignal.unity.ios/Runtime/Plugins/iOS/UIApplication+OneSignalUnity.mm
Fixes iOS build error: No type or protocol named 'OSLiveActivities'
Fixes Unity iOS builds
The Unity iOS plugin bridge files require the following imports instead of being included in OneSignalFramework. OneSignalCore import was added due to LiveActivities being moved into a module in the native OneSignal iOS SDK in version 5.2.0. The swift version of the OneSignalOSCore import seems to be needed due C++ and Objective-C translation. The same issue and fix was also done previously for OSUser.
Tested OneSignal initialization, app build with Unity 2021.3.10f1 of the OneSignal example App on an iPhone 12 with iOS 15.5.
- Simplify with less code, followed by splitting up …
> [Fix] iOS build error: No type or protocol named OSLiveActivities

- com.onesignal.unity.core/Samples~/OneSignalExampleBehaviour.cs
- com.onesignal.unity.core/Samples~/OneSignalExampleScene.unity
Refresh SDK samples from example project
Keep the SDK sample up to date with current functionality.
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/739)
> Refresh SDK samples from example project

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/iOS/ExampleWidget/ExampleWidgetBundle.swift
- OneSignalExample/iOS/ExampleWidget/ExampleWidgetLiveActivity.swift
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
- com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeLiveActivities.mm
Fixes Mac Catalyst build errors: `Use of undeclared identifier 'OneSignalLiveActivitiesManagerImpl'`
Fixes Mac Catalyst build errors with `OneSignalLiveActivitiesManagerImpl`. The `OneSignalLiveActivitiesManagerImpl` module uses `ActivityKit` which is not available for Mac Catalyst and causes build errors.
Fixes live activity build errors for Mac Catalyst builds. However, Unity does not support Mac Catalyst builds either, producing build errors: `Undefined symbol _Unity...`. This PR removes the build errors from OneSignal LiveActivities though.
Tested building for Mac Catalyst, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 17.5.1.
- If it is hard to explain how any codes changes are related to each other then it most likely needs to be more …
> [Fix] Mac Catalyst build errors

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.13 to [5.1.17](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.17) and OneSignal iOS SDK from 5.2.0 to [5.2.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.2)
Applies fixes made in the native SDKs to the Unity wrapper SDK.
Updates included Android SDK from 5.1.13 to [5.1.17](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.17)
- Fixes Xiaomi notification click not foregrounding app
- Fixes FCM push token not being refreshed
- Poll for notification permission changes to detect permission change when prompting outside of OneSignal
- Cold start creates new session and refreshes the user from the server
- Immediately process pending operations when privacy consent goes from false to true …
> [Feat] Bump OneSignal Android and iOS SDK versions

- .github/workflows/set_response_time.yml
Fix issue with response time calculation action failing, re-apply changes in #674 that were lost after merging user model to main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/750)
> [actions] Update set_response_time.yml

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.17 to [5.1.20](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.20) and OneSignal iOS SDK from 5.2.2 to [5.2.3](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.3)
Applies fixes made in the native SDKs to the Unity wrapper SDK.
- Updated included Android SDK from 5.1.17 to [5.1.20](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.20)
- Optimized the initialization process by moving some service initialization to a background thread
- Recover null onesignal ID crashes for Operations
- Add option to default to HMS over FCM
- Prevent retrying IAM display if 410 is received from backend
- Fix dynamic triggers showing IAM repeatedly after being dismissed
- For full changes, see the [native …
> Bump OneSignal Android and iOS SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal iOS SDK from 5.2.3 to [5.2.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.4)
Applies fixes made in the native SDKs to the Unity wrapper SDK.
- Updated included iOS SDK from 5.2.3 to [5.2.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.3)
- Handle incorrect `404` by delaying making updates to new users or subscriptions
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 17.5.1.
- WIP (Work In …
> Bump OneSignal iOS SDK

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Update version numbers of the included native OneSignal SDKs.
Applies fixes from the OneSignal Android SDK and OneSignal iOS SDK to the Unity SDK.
- Updates included Android SDK from 5.1.21 to [5.1.24](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.24)
- Pausing in-app messages now dismisses any currently displaying in-app messages
- Fix setting consentGiven throwing if called before initWithContext
- Fix BadTokenException and WindowLeaked exception caused by showing a dialog on a finishing or destroyed activity
- For full changes, see the [native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Updates included iOS SDK from 5.2.4 to [5.2.7](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.7)
- Pausing in-app messages now …
> Update native OneSignal SDKs

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml
Bump included OneSignal iOS SDK version in the player model version of the OneSignal Unity SDK
Apply the following iOS fix to the Unity SDK for:
[Tapping on launch URLs fails with iOS 18](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1493)
Updates included iOS SDK from 3.12.9 to [3.12.10](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.10)
- Replace deprecated openURL method preventing launch URLs
- Update privacy manifest User Defaults API reason to include app groups
- For full changes, [see the native release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases)
Tested OneSignal initialization, app build with Unity 2021.3.36f1 and Xcode 16.1 of the OneSignal example app on a physical iPhone 12 with iOS 17.5.1. 
- If it is hard to explain how any codes …
> Update the OneSignal iOS SDK version in v3

- com.onesignal.unity.android/Editor/OneSignalConfig.androidlib/build.gradle
Confirmed this change works with Unity 6.0.42f1 and is still compatible with the Unity's oldest LTS, 2021.3.45f1.
Fixes Android build issue with Unity 6 as it's Gradle version requires `namespace` to be defined in the build.gradle.
This addresses Issues:
* https://github.com/OneSignal/OneSignal-Unity-SDK/issues/752
* https://github.com/OneSignal/OneSignal-Unity-SDK/issues/775
SDK should continue to be compatible with newer versions of Unity, without work arounds.
Only effects the Android build process that runs on app developers projects.
No testing suite that builds an app end-to-end in place.
Testing a new Unity project and ensure an Android APK was built successfully on:
* Unity 6.0.42f1
* Unity 2021.3.45f1 (Unity's oldest LTS)
- - -
This change is [<img …
> Fix Unity 6 Android compatibility with gradle

- OneSignalExample/Assets/Plugins/Android/OneSignalConfig.androidlib/build.gradle
- com.onesignal.unity.android/Editor/Migration/MigrateAndroidResources.cs
- com.onesignal.unity.android/Editor/OneSignalConfig.androidlib/build.gradle
- com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs
Automatically apply required changes for Unity 6 build compatibility, this only effects Android.
Follow up to PR https://github.com/OneSignal/OneSignal-Unity-SDK/pull/776
If changes were not applied automatic it will lead extra work the app developer has to search for or may reach out to OneSignal support for help.
Only effects Android builds.
None
Tested with Unity 6000.0.42f1.7976.8784 on macOS.
Made changes to the file located at `Assets/Plugins/Android/OneSignalConfig.androidlib/build.gradle` and ensured it reverts it.
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Unity6; Automatically Android migration

- OneSignalExample/Assets/OneSignal/CHANGELOG.md
- OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle
- OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml
- com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Update OneSignal native SDK to the latest versions.
Applies fixes from the OneSignal Android SDK and OneSignal iOS SDK to the Unity SDK.
Updates both Android and iOS libraries to the latest versions.
None
Just bumping versions, no testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/779)
> Bump native OneSignal SDKs; OneSignal-Android-SDK 5.1.31, OneSignal-iOS-SDK 5.2.10

- com.onesignal.unity.android/Editor/Migration.meta
- com.onesignal.unity.android/Editor/Migration/MigrateAndroidResources.cs.meta
Add missing .meta android migration files that were missed in PR #778.
Resolve error #781 when this SDK is load in the Unity editor.
Only effects the Unity editor loading for Android.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/782)
> Add missing .meta android migration files
