Unity4.7OneSignalExample/Assets/Plugins/OneSignal/Editor/OneSignalEditorScript.cs
Added Platform Dependent Compilation UNITY_EDITOR for successful building on android platform.
=> Only editor execution

CONTRIBUTING.md, README.md, buildpackage.sh, issue_template.md
• Updates the README to be consistent with the other SDK repos
• Adds an issue template and contributing guidelines
=> New readme

OneSignalExample/Assets/OneSignal/Example/GameControllerExample.cs, OneSignalExample/Assets/OneSignal/src/OneSignal.cs
* Renamed "HandlerInAppMessageClicked" to "HandleInAppMessageClicked"
=> Corrected HandleInAppMessageClicked name

OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs, OneSignalExample/Assets/OneSignal/Example/GameControllerExample.cs, OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignal.h, OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignalUnityRuntime.m, OneSignalExample/Assets/OneSignal/src/OneSignal.cs, OneSignalExample/Assets/OneSignal/src/OneSignalIOS.cs
* All trigger methods, pausing, and action click handling
* Fixed PostProcessBuildPlayer_iOS.cs script so frameworks are all added to notification extension service and project
* Minor update to demo app
* Updated OneSignal binary and header
=> IAM functionality added

OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignal.h, OneSignalExample/Assets/OneSignal/Platforms/iOS/OneSignalUnityRuntime.m, OneSignalExample/Assets/OneSignal/src/OneSignal.cs
* Added in all public method bodies for outcome events
* Updated binary for iOS native SDK and the OneSignal header
=> iOS outcome events

OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs
Test on Unity 2019.3.10 and 2017.4.39 on Windows 10. Copied xcode project to macOS 10.15.3 and built with Xcode 11.4 successfully.
* Fixes #287
=> 2019.3.9 broke AddFileToBuild so moved to AddFileToBuildSection

OneSignalExample/Assets/OneSignal/README.md, OneSignalExample/Assets/OneSignal/README.md.meta
* This will be included with the released .unitypackage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/347)
=> Added offline readme.md

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/348)
=> Updated supported devices

com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372)
=> Fixed pathing issues in iOS post processor

composeRelease.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/379)
=> Fixes for a few remaining bugs in the release composer

OneSignalExample/Assets/OneSignal/Example/Scripts/OneSignalExampleBehaviour.cs, com.onesignal.unity.core/Samples~/OneSignalExampleBehaviour.cs
- Removed code requiring C# 8.0 features
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/392)
=> Addressed additional Unity feedback

OneSignalExample/Assets/OneSignal/README.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/383)
=> Added clarity around expanding options for Installation

com.onesignal.unity.core/Runtime/Utilities/MiniJSON.cs
Fix for https://github.com/OneSignal/OneSignal-Unity-SDK/issues/404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/405)
=> MiniJson should be namespaced to the SDK

OneSignalExample/Assets/OneSignal/Attribution/OneSignal.UnityPackage.Attribution.asmdef, OneSignalExample/Assets/OneSignal/Attribution/VspAttribution.cs, OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs, OneSignalExample/Packages/packages-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/406)
=> Add package install check scripting defines

OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalSetupReset.cs, OneSignalExample/Packages/manifest.json, OneSignalExample/Packages/packages-lock.json, com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/407)
=> Fix various issues with running 3.0.0 on Unity 2019

composeRelease.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/408)
=> Add capability to specify version on compose

OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413)
=> Exclude Attribution folder on package creation

OneSignalExample/Assets/OneSignal/Attribution.meta, OneSignalExample/Assets/OneSignal/Attribution/OneSignal.UnityPackage.Attribution.asmdef, OneSignalExample/Assets/OneSignal/Attribution/OneSignal.UnityPackage.Attribution.asmdef.meta, OneSignalExample/Assets/OneSignal/Attribution/VSPAttribution.cs, OneSignalExample/Assets/OneSignal/Attribution/VSPAttribution.cs.meta, OneSignalExample/Assets/OneSignal/Editor/Resources/OneSignalFileInventory.asset, OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs, com.onesignal.unity.core/Runtime/AssemblyInfo.cs, com.onesignal.unity.core/Runtime/Core/OneSignal.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/412)
=> Add VSP to 2.x.x and exclude from locally generated package

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs, com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, com.onesignal.unity.core/Runtime/Models/Notification.cs, com.onesignal.unity.core/Runtime/Models/NotificationAction.cs, com.onesignal.unity.core/Runtime/Models/NotificationOpenedResult.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.Callbacks.cs
- Implemented missing `Notification` properties `additionalData` and `actionButtons`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/425)
=> [Fix] Added missing Notification properties

com.onesignal.unity.android/Runtime/OneSignalAndroid.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/428)
=> Cast outbound log enum so signature is found by JNI

OneSignalExample/Assets/OneSignal/CHANGELOG.md
Just fixing a CHANGELOG entry that missed a commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/440)
=> [FIX] Corrected CHANGELOG

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.core/Editor/SetupSteps/SyncCodeBundleStep.cs
- Checks for VERSION file before attempting to read it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/451)
=> [FIX] Reading missing VERSION file

OneSignalExample/Assets/OneSignal/Attribution/VspAttribution.cs, OneSignalExample/Assets/OneSignal/CHANGELOG.md
- Updated VSP Attribution with the latest version of script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/452)
=> [IMPROVEMENT] Update VSP Attribution

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/OneSignal/Editor/Resources/OneSignalFileInventory.asset, OneSignalExample/Assets/OneSignal/Editor/Utilities.meta, OneSignalExample/Assets/OneSignal/Editor/Utilities/MiniJSON.cs, OneSignalExample/Assets/OneSignal/Editor/Utilities/MiniJSON.cs.meta, OneSignalExample/Assets/OneSignal/Editor/Utilities/ReflectionHelpers.cs, OneSignalExample/Assets/OneSignal/Editor/Utilities/ReflectionHelpers.cs.meta
- Include utilities necessary for independent use of the initial unitypackage install
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/456)
=> [FIX] Missing UnityPackage Utilities

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs
- Updated example code for PostNotification to show an example that works without the API key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/467)
=> [FIX] Updated PostNotification example code

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, com.onesignal.unity.android/Runtime/OneSignalAndroid.Mappings.cs
- Added value to additionalData on Android for NotificationOpened
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/473)
=> [Fix] NotificationOpened additionalData for Android

composeRelease.sh
Automates updating the CHANGELOG for releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462)
=> [FEATURE] Automate updating the CHANGELOG for releases

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, com.onesignal.unity.android/Runtime/OneSignalAndroid.Mappings.cs, com.onesignal.unity.core/Runtime/Models/NotificationAction.cs
- Added value to actionId for Android
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/474)
=> [FIX] ActionID for Android

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs, OneSignalExample/Assets/OneSignal/Example/OneSignalExampleScene.unity, com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs, com.onesignal.unity.core/Runtime/OneSignal.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.cs, com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Added support for `setLaunchURLsInApp`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/459)
=> [IMPROVEMENT] Add support for setLaunchURLsInApp

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, com.onesignal.unity.core/Editor/Platform/OneSignalNative.cs, com.onesignal.unity.core/Runtime/OneSignal.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.Interface.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.cs, com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm
- Reimplemented `disablePush` as `PushEnabled`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/476)
=> [FIX] Missing disablePush

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.core/Runtime/Models/Notification.cs, com.onesignal.unity.ios/Runtime/OneSignalIOS.Mappings.cs
- Added missing Notification fields
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/480)
=> [FIX] Add missing Notification fields

com.onesignal.unity.ios/Runtime/Plugins/iOS/UIApplication+OneSignalUnity.mm
Correct import in #import `UIApplication+OneSignalUnity.m` file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/482)
=> Corrected import

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Runtime/OneSignalAndroid.Mappings.cs
- Error deserialization for identity methods on Android
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/484)
=> [FIX] Error handling on Android

OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- Updated included Android SDK to [4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/486)
=> [FEATURE] Update Android SDK version

MIGRATION.md, OneSignalExample/Assets/OneSignal/CHANGELOG.md, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
- Reorganized migration guide into Added, Updated, and Removed sections
- Added deletion step for legacy AndroidManifest.xml files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/489)
=> Updated migration guide

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
pr template according to this guide https://github.com/OneSignal/sdk-repo-guidance/blob/main/docs/whate-are-pr-templates.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/492)
=> adding a pr template to the .github folder

MIGRATION_GUIDE_v3_to_v5.md, OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/OneSignal/Editor/Resources/OneSignalFileInventory.asset, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v2_to_v3.md, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v2_to_v3.md.meta, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md.meta, OneSignalExample/Assets/OneSignal/README.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, README.md, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.android/Runtime/AndroidNotificationsManager.cs, com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, com.onesignal.unity.core/Runtime/OneSignal.cs, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml, com.onesignal.unity.ios/Runtime/Plugins/iOS/UIApplication+OneSignalUnity.mm
Set the SDK type and SDK version for the SDK header api.
Update the Unity SDK wrapper header with the native api from beta 2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/587)
=> [User Model] Set sdk wrapper headers

MIGRATION_GUIDE_v3_to_v5.md, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md, OneSignalExample/Assets/OneSignal/README.md, README.md
Fix nits in migration guide and readme
Clean up documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/647)
=> [Fix] Documentation nits

MIGRATION_GUIDE_v3_to_v5.md, OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md
Fix note on importing OneSignal assets
Clarify how users can import OneSignal assets through the Unity Asset Store or with our .unitypackage asset attached to every GitHub release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/658)
=> [Fix] Migration guide nit

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK to [5.0.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.4) and OneSignal iOS SDK to [5.0.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.0.4)
Applies native fixes from the OneSignal Android SDK and OneSignal iOS SDK to the Unity SDK
- [OneSignal Android SDK 5.0.4 Release Notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.4)
- [OneSignal iOS SDK 5.0.4 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.0.4)
Tested OneSignal initialization, app build with Unity 2021.3.10f1 of the OneSignal example app on a emulated Pixel 4 with Android 12 and physical iPhone 12 with iOS 15.5.
- If it is hard to explain how any codes changes are related to each other then it most …
=> [Feature] Update native OneSignal SDKs

OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Update dependency version
- Android to 5.1.6
- IOS to 5.1.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/707)
=> Update Android and IOS version number

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.6 to [5.1.7](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.7) and OneSignal iOS SDK from 5.1.3 to [5.1.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.4)
Apply fixes made in the native SDKs to the Unity wrapper SDK.
OneSignal Android SDK changes from 5.1.6 to [5.1.7](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.7)
- Fixes optIn() not prompting if called before push subscription is created on backend
- Fixes crash with EventProducer's fire events
- Fixes context not being set on all entry points
- For full changes, see the [native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
OneSignal iOS SDK changes from 5.1.3 to …
=> [Feat] Bump included OneSignal SDKs

MIGRATION_GUIDE_v3_to_v5.md, README.md
Adds feature parity migration advisory to the migration guide and readme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/721)
=> Add migration warning to readme and migration guide

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Updates included OneSignal Android SDK from 5.1.9 to [5.1.10](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.10) and OneSignal iOS SDK from 5.1.5 to [5.1.6](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.6)
Applies changes and fixes from the native OneSignal SDKs to the Unity wrapper SDK
- Updates included Android SDK from 5.1.9 to [5.1.10](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.10)
- Handles incorrect 404 responses; add a delay after creates and retries on 404 of new ids
- Adds network call optimizations
- For full changes, see the [native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Updates included iOS SDK from 5.1.5 to [5.1.6](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5 …
=> [Feat] Update Android & iOS OneSignal SDKs version

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml
Updates included OneSignal Android SDK from 5.1.20 to [5.1.21](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.21)
Apply fixes made in the native OneSignal Android SDK to the Unity wrapper SDK.
Updated included Android SDK from 5.1.20 to [5.1.21](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.21)
- Fix ending an already ended session
- Fix permissions returned by onRequestPermissionResult when the list is empty
- Fix keyboard input in HTML in-app messages
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a emulated Pixel 4 with Android 12.
- Simplify with less code, followed by …
=> Bump OneSignal Android SDK

OneSignalExample/Assets/OneSignal/CHANGELOG.md, OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle, OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, com.onesignal.unity.ios/Editor/OneSignaliOSDependencies.xml
Update version numbers of the included native OneSignal SDKs.
Applies fixes from the OneSignal Android SDK and OneSignal iOS SDK to the Unity SDK.
- Updated included Android SDK from 5.1.25 to [5.1.26](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.26)
- [Fix] ANR caused by operationRepo.enqueue while loading is in progress
- [Fix] Check subscription Id before executing delete and update subscription operations
- For full changes, see the [native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Updated included iOS SDK from 5.2.8 to [5.2.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.9)
- [Fix] Use new OneSignalClientError type for callbacks which fixes crash report of NSInvalidArgumentException
- [Fix] Don’t evaluate …
=> Update the native OneSignal SDKs

.github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/project.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/786)
=> Add projects workflow
